package org.ad;

import org.openjdk.jcstress.annotations.*;
import org.openjdk.jcstress.infra.results.I_Result;

/**
 *   Observed state   Occurrences              Expectation  Interpretation
 *               10        84,637   ACCEPTABLE_INTERESTING  1 to 20 is possible due to non-atomic operations on volat...
 *               11       120,742   ACCEPTABLE_INTERESTING  1 to 20 is possible due to non-atomic operations on volat...
 *               12       172,543   ACCEPTABLE_INTERESTING  1 to 20 is possible due to non-atomic operations on volat...
 *               13       266,244   ACCEPTABLE_INTERESTING  1 to 20 is possible due to non-atomic operations on volat...
 *               14       421,387   ACCEPTABLE_INTERESTING  1 to 20 is possible due to non-atomic operations on volat...
 *               15       747,821   ACCEPTABLE_INTERESTING  1 to 20 is possible due to non-atomic operations on volat...
 *               16     1,097,878   ACCEPTABLE_INTERESTING  1 to 20 is possible due to non-atomic operations on volat...
 *               17     1,081,693   ACCEPTABLE_INTERESTING  1 to 20 is possible due to non-atomic operations on volat...
 *               18     2,600,772   ACCEPTABLE_INTERESTING  1 to 20 is possible due to non-atomic operations on volat...
 *               19     2,683,562   ACCEPTABLE_INTERESTING  1 to 20 is possible due to non-atomic operations on volat...
 *               20    12,844,774   ACCEPTABLE_INTERESTING  1 to 20 is possible due to non-atomic operations on volat...
 *                4             2   ACCEPTABLE_INTERESTING  1 to 20 is possible due to non-atomic operations on volat...
 *                5             4   ACCEPTABLE_INTERESTING  1 to 20 is possible due to non-atomic operations on volat...
 *                6            10   ACCEPTABLE_INTERESTING  1 to 20 is possible due to non-atomic operations on volat...
 *                7         2,125   ACCEPTABLE_INTERESTING  1 to 20 is possible due to non-atomic operations on volat...
 *                8        10,695   ACCEPTABLE_INTERESTING  1 to 20 is possible due to non-atomic operations on volat...
 *                9        26,732   ACCEPTABLE_INTERESTING  1 to 20 is possible due to non-atomic operations on volat...
 */
@JCStressTest
@State
@Outcome(expect = Expect.ACCEPTABLE_INTERESTING, desc = "1 to 20 is possible due to non-atomic operations on volatile field")
public class NonAtomic {
    volatile int x;

    @Actor
    void actor1() {
        for (int i = 0; i < 10; i++) {
            x++;
        }
    }

    @Actor
    void actor2() {
        for (int i = 0; i < 10; i++) {
            x++;
        }
    }

    @Arbiter
    public void arbiter(I_Result r) {
        r.r1 = x;
    }
}
